# Generated by Django 4.0.4 on 2022-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0002_rename_title_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='provide value for each', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
