# Generated by Django 4.0.4 on 2022-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0004_alter_trainers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('website', models.CharField(max_length=200, unique=True)),
                ('comment', models.TextField(max_length=200, unique=True)),
            ],
        ),
    ]
