# Generated by Django 4.0.4 on 2022-06-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
