# Generated by Django 4.0.4 on 2022-06-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0006_rename_contact_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='comment',
            new_name='message',
        ),
    ]
