# Generated by Django 4.0.4 on 2022-06-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0007_rename_comment_contactform_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
