# Generated by Django 4.0.5 on 2022-06-15 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0008_rename_contactform_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='email',
            field=models.CharField(default='timezone.now as a value', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='fb_account',
            field=models.CharField(default='provide value for each', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='insta_account',
            field=models.CharField(default='provide value for each', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='twitter_account',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='youtube_account',
            field=models.CharField(default='timezone.now', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
