# Generated by Django 4.0.5 on 2022-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0009_trainers_email_trainers_fb_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='email',
            new_name='trainer_email',
        ),
    ]
