# Generated by Django 4.0.5 on 2022-06-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0010_rename_email_trainers_trainer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
